listeners:
- query_port: 25565
  motd: |-
    §a                TelixMC §4[1.16-1.19]§r
    §4                    SMP §f| §4PVP
  tab_list: GLOBAL
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - Lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 200000
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  admin:
  - bungeecord.command.alert
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 28deaafe-1ae0-48b7-b0e5-c3e8d3ddf80a
player_limit: -1
ip_forward: true
groups:
  TheGuyCode:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  Lobby:
    motd: |-
      §a                TelixMC §4[1.16-1.19]§r
      §4                    SMP §f| §4PVP
    address: localhost:25767
    restricted: false
  KitPVP:
    motd: |-
      §a                TelixMC §4[1.16-1.19]§r
      §4                    SMP §f| §4PVP
    address: localhost:25575
    restricted: false
